In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data = {'Position':['CEO', 'Chairman', 'Director', 'Senior Manager', 'Junior Manager', 'Intern'],
        'Level':[1, 2, 3, 4, 5, 6],
        'Salary':[50000, 80000, 110000, 150000, 200000, 2500000]}
df = pd.DataFrame(data)

X = df.iloc[:, 1:2].values
Y = df.iloc[:, 2].values

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

print("X_train:\n", X_train)
print("y_train:\n", Y_train)
print("X_test:\n", X_test)
print("y_text:\n", Y_test)

regressor = LinearRegression()
regressor.fit(X_train, Y_train)

print("Coefficients: ", regressor.coef_)
print("Intercept: ", regressor.intercept_)

X_train:
 [[2]
 [4]
 [1]
 [5]]
y_train:
 [ 80000 150000  50000 200000]
X_test:
 [[6]
 [3]]
y_text:
 [2500000  110000]
Coefficients:  [37000.]
Intercept:  9000.00000000003
