Create ‘Salary’ Data set . Build a linear regression model by identifying independent and target variable. Split the variables into training and testing sets and print them. Build a simple linear regression model for predicting purchases.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
# Create the Salary dataset
data = {'YearsExperience': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
'Salary': [50000, 60000, 70000, 80000, 90000, 100000, 110000, 120000, 130000, 140000]}

df = pd.DataFrame(data)

X = df.iloc[:, 0:1].values
Y = df.iloc[:, 1].values

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

print("X_train:\n", X_train)
print("y_train:\n", Y_train)
print("X_test:\n", X_test)
print("y_test:\n", Y_test)

regressor = LinearRegression()
regressor.fit(X_train, Y_train)

print("Coefficients:", regressor.coef_)
print("Intercept:", regressor.intercept_)

X_train:
 [[10]
 [ 2]
 [ 7]
 [ 8]
 [ 4]
 [ 1]
 [ 6]]
y_train:
 [140000  60000 110000 120000  80000  50000 100000]
X_test:
 [[3]
 [9]
 [5]]
y_test:
 [ 70000 130000  90000]
Coefficients: [10000.]
Intercept: 39999.999999999985
